config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false
  excludes: []

processors:
  active: true

console-reports:
  active: true

comments:
    AbsentOrWrongFileLicense:
        active: false
    UndocumentedPublicClass:
        active: false
    UndocumentedPublicFunction:
        active: false
    UndocumentedPublicProperty:
        active: false

complexity:
    ComplexCondition:
        allowedConditions: 4
    ComplexInterface:
        ignoreOverloaded: true
    LabeledExpression:
        active: false
    LongParameterList:
        allowedFunctionParameters: 6
        allowedConstructorParameters: 7
    StringLiteralDuplication:
        allowedDuplications: 3
    TooManyFunctions:
        allowedFunctionsPerInterface: 12 # Default is 11, but [Assertion.Builder] has more functions, so we set it to 12.
        ignoreDeprecated: true
        ignoreInternal: true
        ignoreOverridden: true
        ignorePrivate: true

naming:
    FunctionNameMaxLength:
        maximumFunctionNameLength: 40
    VariableMinLength:
        minimumVariableNameLength: 3

performance:
    CouldBeSequence:
        allowedOperations: 2

potential-bugs:
    CastNullableToNonNullableType:
        ignorePlatformTypes: true
    LateinitUsage:
        excludes: []
    UnnamedParameterUse:
        allowAdjacentDifferentTypeParams: false
        allowSingleParamUse: false
        ignoreArgumentsMatchingNames: false

style:
    AlsoCouldBeApply:
        active: false
    BracesOnIfStatements:
        singleLine: 'necessary'
        multiLine: 'always'
    CascadingCallWrapping:
        includeElvis: false
    DataClassContainsFunctions:
        active: false
    EqualsOnSignatureLine:
        active: false
    ExpressionBodySyntax:
        includeLineWrapping: true
    ForbiddenComment:
        comments:
          - reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
            value: 'FIXME:'
          - reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'
            value: 'STOPSHIP:'
          - reason: 'Forbidden TODO todo marker in comment, please do the changes.'
            value: 'TODO:'
          - reason: 'Use @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE) instead.'
            value: '^private$'
    ForbiddenSuppress:
        active: false
    MagicNumber:
        ignorePropertyDeclaration: true
        ignoreRanges: true
    MaxChainedCallsOnSameLine:
        maxChainedCalls: 3
    UnnecessaryParentheses:
        allowForUnclearPrecedence: true
    UseIfInsteadOfWhen:
        active: false
